version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:17.6
    restart: always
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pg_db
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on: 
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    restart: unless-stopped

volumes:
  postgres_data: